export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR'

export const REMOVE_FROM_CART_REQUEST = 'REMVOE_FROM_CART_REQUEST'
export const REMOVE_FROM_CART_SUCCESS = 'REMVOE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_ERROR = 'REMVOE_FROM_CART_ERROR'

export const CART_RESET_REQUEST = 'CART_RESET_REQUEST'
export const CART_RESET_SUCCESS = 'CART_RESET_SUCCESS'
export const CART_RESET_ERROR = 'CART_RESET_ERROR'


export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_ERROR = "GET_PRODUCT_DETAILS_ERROR";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";